name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run script
      run: |
        chmod +x script.sh
        ./script.sh

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build APK
      run: |
        cd JavaGoat
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: NexChat-APK
        path: JavaGoat/app/build/outputs/apk/debug/app-debug.apk
